interface: eno1
type: afpacket
connection_timeout: 10
update_analyzers: false
analyzers:
  github.com/gourmetproject/dnsanalyzer:
  github.com/gourmetproject/bedtimeanalyzer:
    threshold: 10
    bedtime_bot_token: token_goes_here
    my_user_id: uid_goes_here

