interface: eth0
type: afpacket
analyzers:
  github.com/gourmetproject/dnsanalyzer:
  github.com/gourmetproject/bedtimeanalyzer:
    depends_on:
      - github.com/gourmetproject/dnsanalyzer
    bedtime_bot_token: your_token_here
    my_user_id: your_user_id_here
